### ISSUE TITLE
I use tensorboard --logdir=logs to view training information and real-time training

### ISSUE THREAD

**Issue by Gj-12222** [opendilab/GoBigger-Challenge-2021#11]
Error: 
Traceback (most recent call last):
  File "E:\software\Anconada\envs\gobiggermaster\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "E:\software\Anconada\envs\gobiggermaster\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\software\Anconada\envs\gobiggermaster\Scripts\tensorboard.exe\__main__.py", line 7, in <module>
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\main.py", line 64, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\program.py", line 220, in main
    server = self._make_server()
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\program.py", line 302, in _make_server
    return self.server_class(app, self.flags)
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\program.py", line 392, in init
    return cls(wsgi_app=wsgi_app, flags=subflags)
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\program.py", line 425, in __init__
    super(WerkzeugServer, self).__init__(host, port, wsgi_app)
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\werkzeug\serving.py", line 740, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "E:\software\Anconada\envs\gobiggermaster\lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "E:\software\Anconada\envs\gobiggermaster\lib\site-packages\tensorboard\program.py", line 500, in server_bind
    super(WerkzeugServer, self).server_bind()
  File "E:\software\Anconada\envs\gobiggermaster\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "E:\software\Anconada\envs\gobiggermaster\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 0: invalid start byte

**Comment by mingzhang96** [comment]
Thanks for your issue!
Please ensure that no Chinese characters appear in the command path or the log path.

**Comment by Gj-12222** [comment]
Thanks!
