### ISSUE TITLE
请问一下这个提供的例子是不是不兼容新版本的DI-engine

### ISSUE THREAD

**Issue by atiyit** [opendilab/GoBigger-Challenge-2021#15]
没有办法复现，提示
Traceback (most recent call last):
  File "gobigger_selfplay_baseline_main.py", line 15, in <module>
    from envs import GoBiggerEnv
  File "..\envs\__init__.py", line 1, in <module>
    from .gobigger_env import GoBiggerEnv
  File "..\envs\gobigger_env.py", line 8, in <module>
    from ding.envs import BaseEnv, BaseEnvTimestep, BaseEnvInfo
ImportError: cannot import name 'BaseEnvInfo' from 'ding.envs' (C:\Users\abc\Anaconda3\envs\qiuqiu\lib\site-packages\ding\envs\__init__.py)

注释掉BaseEnvInfo和相关方法会提示
Traceback (most recent call last):
  File "C:\Users\abc\Anaconda3\envs\qiuqiu\lib\site-packages\ding\envs\env_manager\base_env_manager.py", line 111, in __init__
    self._observation_space = self._env_ref.observation_space
AttributeError: 'GoBiggerEnv' object has no attribute 'observation_space'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gobigger_selfplay_baseline_main.py", line 106, in <module>
    main(main_config)
  File "gobigger_selfplay_baseline_main.py", line 55, in main
    env_fn=[lambda: GoBiggerEnv(collector_env_cfg) for _ in range(collector_env_num)], cfg=cfg.env.manager
  File "C:\Users\abc\Anaconda3\envs\qiuqiu\lib\site-packages\ding\envs\env_manager\subprocess_env_manager.py", line 216, in __init__
    super().__init__(env_fn, cfg)
  File "C:\Users\abc\Anaconda3\envs\qiuqiu\lib\site-packages\ding\envs\env_manager\base_env_manager.py", line 120, in __init__
    self._env_ref.reset()
  File "..\envs\gobigger_env.py", line 69, in reset
    self._env = self._launch_game()
  File "..\envs\gobigger_env.py", line 61, in _launch_game
    server.start()
AttributeError: 'Server' object has no attribute 'start'

**Comment by jayyoung0802** [comment]
Hi, thanks to your attention, GoBigger is updating, and new version will come soon!
If you want to try this old version, maybe you can try the following:
GoBigger:   [pip install gobigger==0.1.5](https://github.com/opendilab/GoBigger/releases/tag/v0.1.5)
DI-engine:  (https://github.com/opendilab/DI-engine/releases/tag/v0.2.3)

**Comment by LYK0520** [comment]
AttributeError: 'GoBiggerEnv' object has no attribute 'observation_space'
我一样遇到这样的问题，请问现在有解决吗

**Comment by jayyoung0802** [comment]
Hi, add  self._observation_space=None, self._action_space=None, self._reward_space=None and the following function in env.



    @property
    def observation_space(self) -> gym.spaces.Space:
        # The following ensures compatibility with the DI-engine Env class.
        return self._observation_space

    @property
    def action_space(self) -> gym.spaces.Space:
        # The following ensures compatibility with the DI-engine Env class.
        return self._action_space

    @property
    def reward_space(self) -> gym.spaces.Space:
        # The following ensures compatibility with the DI-engine Env class.
        return self._reward_space
